# Generated by Django 4.2.7 on 2024-10-31 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_coach',
            field=models.BooleanField(default=False),
        ),
    ]
